name = "preferred-ips"
main = "worker.js"
compatibility_date = "2026-08-17"
workers_dev = false

# KV 命名空间（与线上一致）
[[kv_namespaces]]
binding = "PREFERRED_IPS"
id = "44bc3ee0aa834504bf697b9f7896cfc3"

# 管理/接口登录密钥（与线上一致）
# 注意：这是明文写进文件，建议后续改用 wrangler secret put AUTH_KEY 更安全
[vars]
AUTH_KEY = "78b997b960fd"

# 自定义域名（与线上一致）
[[routes]]
pattern = "preferred-ips.toworld.uk"
zone_name = "toworld.uk"
custom_domain = true
